import { MDP_TOOLBAR_HEIGHT_FALLBACK_PX, SCROLL_PADDING_PX } from '../shared/constants/viewer.js'

const HEADING_WITH_ID_SELECTOR = 'h1[id],h2[id],h3[id],h4[id],h5[id],h6[id]'

function decodeHashTarget(value) {
  if (!value) return ''
  try {
    return decodeURIComponent(value)
  } catch {
    return value
  }
}

function encodeHashTarget(value) {
  const raw = String(value || '').replace(/^#/, '')
  if (!raw) return ''

  try {
    const decoded = decodeURIComponent(raw)
    if (encodeURIComponent(decoded) === raw) {
      return raw
    }
  } catch {
    /* fall through to normal encoding */
  }

  return encodeURIComponent(raw)
}

function getHashTargetCandidates(hash) {
  const raw = String(hash || '').replace(/^#/, '')
  if (!raw) return []

  const decoded = decodeHashTarget(raw)
  return Array.from(new Set([
    raw,
    decoded,
    encodeHashTarget(raw),
    encodeHashTarget(decoded)
  ].filter(Boolean)))
}

function findElementById(root, id) {
  if (!root || !id) return null

  if (typeof root.querySelector === 'function' && globalThis.CSS?.escape) {
    try {
      const match = root.querySelector(`#${CSS.escape(id)}`)
      if (match) return match
    } catch {
      /* fall through to exact id scan */
    }
  }

  if (typeof root.querySelectorAll !== 'function') return null
  for (const element of root.querySelectorAll('[id]')) {
    if (element.id === id) return element
  }
  return null
}

/**
 * Encode a heading id/hash for location.hash without double-encoding IDs generated by
 * markdown-it-anchor, which already percent-encodes Unicode and emoji slug segments.
 * @param {string} value
 * @returns {string}
 */
export function hashTargetToUrlFragment(value) {
  const encoded = encodeHashTarget(value)
  return encoded ? `#${encoded}` : ''
}

/**
 * Find a rendered heading by URL hash. Heading IDs may be either decoded custom IDs or
 * percent-encoded markdown-it-anchor slugs, so try both forms.
 * @param {ParentNode | null | undefined} root
 * @param {string} hash
 * @returns {Element | null}
 */
export function findHeadingByHash(root, hash) {
  if (!root || !hash) return null
  for (const candidate of getHashTargetCandidates(hash)) {
    const element = findElementById(root, candidate)
    if (element?.matches?.(HEADING_WITH_ID_SELECTOR)) return element
  }
  return null
}

/**
 * Scroll so `element` aligns near the top of the viewer scroll root, or fall back to window scroll.
 *
 * @param {object} options
 * @param {Element} options.element
 * @param {Element | null} [options.scrollRoot] - `.mdp-root` when present
 * @param {number} [options.toolbarHeight] - top offset in px (0 when no top chrome)
 * @param {ScrollBehavior} [options.behavior]
 */
export function scrollToElementInViewer({
  element,
  scrollRoot = null,
  toolbarHeight = MDP_TOOLBAR_HEIGHT_FALLBACK_PX,
  behavior = 'auto'
} = {}) {
  if (!element) return

  const offset = toolbarHeight + SCROLL_PADDING_PX

  if (scrollRoot && typeof scrollRoot.scrollTo === 'function') {
    const rootRect = scrollRoot.getBoundingClientRect()
    const elRect = element.getBoundingClientRect()
    const targetTop = elRect.top - rootRect.top + scrollRoot.scrollTop - offset
    scrollRoot.scrollTo({ top: targetTop, behavior })
    return
  }

  const top = element.getBoundingClientRect().top + window.scrollY - offset
  window.scrollTo({ top, behavior })
}

/**
 * Top chrome offset inside a viewer scroll root.
 * @param {Element | null | undefined} scrollRoot
 * @returns {number}
 */
export function getToolbarHeightInScrollRoot(scrollRoot) {
  void scrollRoot
  return MDP_TOOLBAR_HEIGHT_FALLBACK_PX
}
